name: Coredns Build

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Build
      run: |
        curl -O -L "https://golang.google.cn/dl/go1.20.1.linux-amd64.tar.gz"
        tar xzf "go1.20.1.linux-amd64.tar.gz"
        export GOROOT=$(pwd)/go
        export PATH=$(pwd)/go/bin:$PATH
        export GO111MODULE=on
        go version
        git clone https://github.com/missdeer/coredns_custom_build.git
        git clone https://github.com/coredns/coredns.git
        cp coredns_custom_build/prepare.sh coredns
        cp coredns_custom_build/build-custom-coredns-lite.sh .
        cp coredns_custom_build/build-custom-coredns.sh .
        cd coredns
        ./prepare.sh
        cd ..
        ./build-custom-coredns.sh
        cp -f patch/coredns-plugin.cfg coredns/plugin.cfg
        cd coredns
        make
        rm -rf coredns
        export GOOS=linux && export GOARCH=arm64 && make PREFIX=linux-arm64 SUFFIX= HOST=linux
        cd ..
        mkdir binary
        cp coredns/coredns binary
        ls
        pwd

    - name: Upload
      uses: actions/upload-artifact@main
      with:
        name: coredns-build
        path: binary

